services:
  - type: web
    name: skill-setu
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM
        value: Skill Setu <onboarding@resend.dev>
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: FRONTEND_URL
        value: https://skill-setu.netlify.app
      - key: TWILIO_ACCOUNT_SID
        value: AC340005e8778637f3871b65063cee4022
      - key: TWILIO_AUTH_TOKEN
        value: d39bbc9a20fd82db1b854f89a224690b
      - key: TWILIO_PHONE_NUMBER
        value: +18148940613
